export default {
  EVENTS_RECEIVED: "EVENTS_RECEIVED",
  EVENTITEM_RECEIVED: "EVENTITEM_RECEIVED",
  EVENTITEM_LOADING: "EVENTITEM_LOADING",
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGGEDIN: "USER_LOGGEDIN",
  USER_LOGOUT: "USER_LOGOUT",
  EVENTS_ADDPARTICIPANT: "EVENTS_ADDPARTICIPANT",
  LOCATIONS_RECEIVED: "LOCATIONS_RECEIVED",
  LOCATIONITEM_RECEIVED: "LOCATIONITEM_RECEIVED",
  LOCATIONITEM_LOADING: "LOCATIONITEM_LOADING"
};
